name: macro_calculator
description: A new Flutter project.
version: 4.0.0+8

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: any
  intl : any
  shared_preferences: any
  flutter_pw_validator: any
  cupertino_icons: ^1.0.5
  eva_icons_flutter: ^3.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  numberpicker: ^2.1.1
  path_provider: ^2.0.11
  provider: ^6.0.3
  screenshot: ^1.2.3
  share_plus: ^4.0.10
  fl_chart: any


dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
